POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTc3MjY0MjY1NiwidXNlcklkIjoyfQ.smEvjURW5XfQyHi0Gb_UiKyU2ZBtgdNsg4cmsrVQSQo

{
    "name":"ram",
    "description":"walk",
    "location":"delhi",
    "datetime":"2026-03-01T15:30:00.00Z"
}