POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGdtYWlsLmNvbSIsImV4cCI6MTc3MjY0ODYxNywidXNlcklkIjozfQ.s4rJD8f_rMiF5cazQqYHQckpneYKgJkGe9ghO1ilQX8

{
    "name":"ram",
    "description":"walk",
    "location":"delhi",
    "datetime":"2026-03-01T15:30:00.00Z"
}