POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImV4cCI6MTc3MjY1MDA2MCwidXNlcklkIjoxfQ.MRSoprO0cx5nm7UF0scXADjClQRJQzyPTxdRFqzzh2Q

{
    "name":"ram",
    "description":"walk",
    "location":"delhi",
    "datetime":"2026-03-01T15:30:00.00Z"
}