DELETE http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImV4cCI6MTc3MjY1MDA2MCwidXNlcklkIjoxfQ.MRSoprO0cx5nm7UF0scXADjClQRJQzyPTxdRFqzzh2Q