DELETE http://localhost:8080/events/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGdtYWlsLmNvbSIsImV4cCI6MTc3MjY0ODYxNywidXNlcklkIjozfQ.s4rJD8f_rMiF5cazQqYHQckpneYKgJkGe9ghO1ilQX8