PUT http://localhost:8080/events/5
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGdtYWlsLmNvbSIsImV4cCI6MTc3MjY0ODYxNywidXNlcklkIjozfQ.s4rJD8f_rMiF5cazQqYHQckpneYKgJkGe9ghO1ilQX8

{
    "name":"this_is updated",
    "description":"another test event",
    "location":"a test location",
    "dateTime":"2026-03-03T12:30:00Z"
}