PUT http://localhost:8080/events/1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImV4cCI6MTc3MjY1MDA2MCwidXNlcklkIjoxfQ.MRSoprO0cx5nm7UF0scXADjClQRJQzyPTxdRFqzzh2Q

{
    "name":"this_is updated",
    "description":"another test event",
    "location":"a test location",
    "dateTime":"2026-03-03T12:30:00Z"
}